language: objective-c
osx_image: xcode7.3

script:
  - xctool -workspace Tester.xcworkspace -scheme Tester  ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Tester.xcworkspace -scheme Tester -destination ONLY_ACTIVE_ARCH=NO
