language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace Tester.xcworkspace -scheme Tester -sdk iphonesimulator build test
  #- xctool -workspace Tester.xcworkspace -scheme Tester -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO
  #- xctool test -workspace Tester.xcworkspace -scheme Tester -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO
