language: objective-c
osx_image: xcode7.3

script:
  - xctool -workspace Tester.xcworkspace -scheme Tester -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1 ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Tester.xcworkspace -scheme Tester -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1" ONLY_ACTIVE_ARCH=NO
